
from: sender@example.com
username: sender@example.com
password: Sender Password
receiver: receiver@example.com
smtp server: smtp.gmail.com
smtp port: 465

---

- url: https://www.kijiji.ca/b-markham-york-region/bikes/k0l1700274?ll=43.879401%2C-79.414110&address=23+Farmstead+Rd%2C+Richmond+Hill%2C+ON+L4S+1V8%2C+Canada&radius=50.0&dc=true